services:
  - type: web
    name: ai-backend
    env: python
    plan: free
    rootDir: AI_Code_Assistant_backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13

      - key: GROQ_API_KEY
        value: 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